=begin
Project Euler Problem 44
Written By Alan Bishop 6/11/14

"Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?"

=end

class Integer
    def isPentagonal?
        invTest = (Math.sqrt(24*self + 1) +1/6)     
        return (self == PentagonalNum(invTest))
    end
end

def PentagonalNum(n)
    return (n * (3*n -1))/2
end

notFound = true
while notFound do


end
