=begin
Project Euler Problem 45
Written By Alan Bishop 6/6/14


"Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle        Tn=n(n+1)/2         1, 3, 6, 10, 15, ...
Pentagonal      Pn=n(3n−1)/2        1, 5, 12, 22, 35, ...
Hexagonal       Hn=n(2n−1)      1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal."
=end


start = Time.now

def nextTriangleNum(n)
    return (n*(n+1))/2
end

def nextPentagonalNum(n)
    return (n*(3*n-1))/2
end

def nextHexagonalNum(n)
    return n*(2*n-1)
end

#We have certain values already...
triNum = 40755
triN = 285
pentNum = 40755
pentN = 165
hexNum = 40755
hexN = 143

#Start looking for next number
triN += 1
triNum = nextTriangleNum(triN)
while !(triNum == pentNum && triNum == hexNum) do
    if(pentNum < triNum)
        pentN += 1
        pentNum = nextPentagonalNum(pentN)
    elsif(hexNum < triNum)
        hexN += 1
        hexNum = nextHexagonalNum(hexN)
    else
        triN +=1
        triNum = nextTriangleNum(triN)
    end
end 

puts "Next triangle number that is also pentagonal and hexagonal is #{triNum}"

puts "Elapsed time: #{Time.now-start}"
